### ISSUE TITLE
dependencies

### ISSUE THREAD

**Issue by jeongyoonlee** [floydwch/kaggle-cli#1]
I needed to install additional packages to make it work as follows:

```
pip install stevedore PrettyTable cmd2
```

**Comment by floydsoft** [comment]
@jeongyoonlee Hmm... these dependencies is listed in https://github.com/dhellmann/cliff/blob/master/requirements.txt though.

So you have encountered problems in pip installation?

**Comment by UniqueFool** [comment]
FYI: I ended up having to install python-lxm

**Comment by floydwch** [comment]
I'm cleaning the issue list, if you still have the problem, feel free to reopen it.
