### ISSUE TITLE
re-factor

### ISSUE THREAD

**Issue by yitang** [floydwch/kaggle-cli#11]
Hi, there's three way to run `kg`, 1) load username/password from user configuration file, 2) load username/password from current working directory, 3) set username/password on command line. I wonder if it is worth making the third method deprecated, then we could refactor the code to have a single module for loading username/password.

**Comment by floydwch** [comment]
Don't realize your suggestion very well, but the auth function has been refactored to a single one.

See https://github.com/floydwch/kaggle-cli/blob/master/kaggle_cli/common.py#L68-L83 .

I'm cleaning the issue list, if you still have the problem, feel free to reopen it.
