### ISSUE TITLE
Throw error when an html file is returned from a download request

### ISSUE THREAD

**Issue by nateGeorge** [floydwch/kaggle-cli#12]
If a username or password is incorrect and someone tries to download files, the files will still be downloaded with their names, but the size will be much smaller than it should be and it will be an HTML file.  I tried logging in with the CLI using my Google creds, and instead of downloading files, it downloaded HTML responses.  It would be nice if the CLI could catch this error.  

Maybe it could also try to first successfully login (or maybe try to download a small file from some competition) when the config username and password are set, and then report if the username or password is wrong.  In the case of downloading a file, this could try to unzip the file, then if it fails, check if it's actually HTML, and if it is HTML, report an error 'incorrect password and/or username'.

An example of the returned HTML is contained in the attached zip.
[train.html.zip](https://github.com/floydwch/kaggle-cli/files/405828/train.html.zip)

**Comment by yitang** [comment]
i get the html files even after fix usename/password. not sure what's the problem. 


![image](https://cloud.githubusercontent.com/assets/6054101/18931178/01427322-85c3-11e6-9c19-e9b06161a592.png)

**Comment by nateGeorge** [comment]
Are you sure you have an actual kaggle account?  You aren't just using a
linked gmail account?

**Comment by yitang** [comment]
@nateGeorge i found there's a conflict in configuration. the global configuration has a higher priority if it is set. This is count-intuitive for me. I thought the command line arguments have higher priority.
