### ISSUE TITLE
`kg download` after globally setting username, password, and competition fails

### ISSUE THREAD

**Issue by nateGeorge** [floydwch/kaggle-cli#15]
I first did

```
kg config -g -u USERNAME -p PASSWORD -c COMPETITION
```

then

```
kg download
```

and it returned the error

```
There was an error logging in: The User name field is required.
The Password field is required.
```

**Comment by VedAustin** [comment]
Why am I getting this?
```
kg: 'download' is not a kg command. See 'kg --help'.
│Did you mean one of these?
|  complete
```

**Comment by floydwch** [comment]
Something might go wrong between global and local config. Suggest you to remove the `.kaggle-cli` under the project or home dir manually.

I'm cleaning the issue list, if you still have the problem, feel free to reopen it.
