### ISSUE TITLE
download page HTML changed, `kg download` not working

### ISSUE THREAD

**Issue by tschottdorf** [floydwch/kaggle-cli#22]
Assuming that I'm not completely confused, I think Kaggle just changed its HTML code and as a result, (at the very least) downloading datasets doesn't work any more; for example, https://www.kaggle.com/c/the-nature-conservancy-fisheries-monitoring/data contains no `data-files` div any more, leading to the stack trace

```
https://www.kaggle.com:443 "GET /account/login HTTP/1.1" 200 5203

https://www.kaggle.com:443 "POST /account/login HTTP/1.1" 302 133
https://www.kaggle.com:443 "GET /account/welcome HTTP/1.1" 302 118
https://www.kaggle.com:443 "GET / HTTP/1.1" 200 9978
https://www.kaggle.com:443 "GET /c/the-nature-conservancy-fisheries-monitoring/data HTTP/1.1" 200 25109

  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/kaggle_cli/download.py", line 30, in take_action
    links = data_page.soup.find(id='data-files').find_all('a')
AttributeError: 'NoneType' object has no attribute 'find_all'
```

**Comment by tschottdorf** [comment]
This patch fixes it for the time being, as ugly as it looks. A non-hacky way to get the file names, it seems, would involve parsing the react JS.

```diff
diff --git a/kaggle_cli/download.py b/kaggle_cli/download.py
index 201e9cd..70f9d48 100644
--- a/kaggle_cli/download.py
+++ b/kaggle_cli/download.py
@@ -24,11 +24,14 @@ class Download(Command):
         data_url = '/'.join([base, 'c', competition, 'data'])

         data_page = browser.get(data_url)
-        links = data_page.soup.find(id='data-files').find_all('a')
+        import re
+
+        data=str(data_page.soup)
+        links=re.findall('"url":"(/c/'+competition+'/download/[^"]+)"', data)

         for link in links:
-            if file_name is None or link.get('name') == file_name:
-                url = base + link.get('href')
+            if file_name is None: # downloading single file not suported in this hack
+                url = base + link
                 self.download_file(browser, url)

     def download_file(self, browser, url):
```

**Comment by fazzolini** [comment]
@tschottdorf how do I use this fix?

**Comment by fazzolini** [comment]
I have the same issue, the downloads do not work anymore, I properly set up username, password and competition name. I do now use social networks to log into Kaggle. However, I get the following error:
`NoneType' object has no attribute 'find_all`

**Comment by floydwch** [comment]
@tschottdorf thanks for your report, the issue has been confirmed, and could you send a PR?

**Comment by tschottdorf** [comment]
I can submit something like the above solution, though I consider it pretty ugly - probably better than having it completely broken though. It's that what you suggested?

**Comment by floydwch** [comment]
Well, in the meanwhile, it's a good enough solution. I've viewed the latest Kaggle's src, and they just built their site to the dynamic content flavor.

On the other hand, data scientists seek signals in the dirt (maybe ugly more) all the day. I think it's OK to adopt such solution.

**Comment by jon-choi** [comment]
Thank you for this fix! Waiting eagerly :)

**Comment by tschottdorf** [comment]
PR is open: https://github.com/floydwch/kaggle-cli/pull/23

**Comment by Shoshin23** [comment]
I had the same error. doing a pip install kaggle-cli --upgrade helped me resolve the problem. Just letting everyone else know.
