### ISSUE TITLE
Missing cliff dependency

### ISSUE THREAD

**Issue by marc-lopez** [floydwch/kaggle-cli#24]
OS: Windows 10

Python environment: Anaconda2

Command used: `pip install kaggle-cli`

Error received:
```
   Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\marc\appdata\local\temp\pip-build-_0jqmc\kaggle-cli\setup.py", line 4, in <module>
        from kaggle_cli.main import VERSION
      File "kaggle_cli\main.py", line 2, in <module>
        from cliff.app import App
    ImportError: No module named cliff.app
```

**Comment by rdefeo** [comment]
It its preventing me also from perform pip install in any way I have tried.

**Comment by rdefeo** [comment]
I managed to work around the problem by installing the dependency manually, http://docs.openstack.org/developer/cliff/install.html#python-versions

**Comment by mfsteen** [comment]
I had a similar problem and rdefeo's solution worked for me:
pip install cliff
pip install kaggle-cli

**Comment by floydwch** [comment]
fixed via https://github.com/floydwch/kaggle-cli/commit/399589542499069a2651e133de7c5ba3e0412797
