### ISSUE TITLE
Problem in configure after installation

### ISSUE THREAD

**Issue by joaosauer** [floydwch/kaggle-cli#25]
Hi,

I'm running it on windows 10 with python installed and the Kaggle-cli being installed using the pip command.
After the installation I'm getting:
C:\>kg config
'module' object is not callable

Any idea what should I do?

Thanks,
joao

**Comment by floydwch** [comment]
What's your Python version?

**Comment by joaosauer** [comment]
Thanks for the quickly response.
Here is the version:
C:\>python --version
Python 2.7.13

**Comment by floydwch** [comment]
Can you try to `from configparser import ConfigParser` in your Python prompt, and inspect `ConfigParser`. i.e. :

```
>>> from configparser import ConfigParser
>>> ConfigParser
<class 'backports.configparser.ConfigParser'>
```

**Comment by joaosauer** [comment]
Sure,
Here is the result:
C:\>python
Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from configparser import ConfigParser
>>> ConfigParser
<module 'ConfigParser' from 'C:\Python27\lib\ConfigParser.pyc'>

**Comment by floydwch** [comment]
It's weird. Can you evaluate:

```
>>> import configparser
>>> configparser
<module 'configparser' from '/Users/floydwch/.pyenv/versions/2.7.9/lib/python2.7/site-packages/configparser.pyc'>
```

**Comment by joaosauer** [comment]
Now is different:

C:\>python
Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
```
>>> import configparser
>>> configparser
<module 'configparser' from 'D:\Joao\DL_training\theano\Theano\configparser.pyc'>
```

**Comment by floydwch** [comment]
It seems that the loading path is hijacked by the local theano. Maybe you have to install theano globally. i.e. `pip install theano`.

**Comment by joaosauer** [comment]
I installed Theano using the pip command... :(

**Comment by joaosauer** [comment]
I found the problem.
I had the Theano folder in the PYTHONPATH.
Removing it from there makes the Kg command to work!
Thanks a lot for your help!
