### ISSUE TITLE
Error with no config file

### ISSUE THREAD

**Issue by jalandis** [floydwch/kaggle-cli#26]
reduce() of empty sequence with no initial value

**Comment by floydwch** [comment]
Thanks for the report, I fixed it via a similar way. See https://github.com/floydwch/kaggle-cli/commit/0521b154ab869ceb93d76787b515988e2d0a28bc and https://github.com/floydwch/kaggle-cli/commit/f3d966906e8ad3861e9d93b94a933e2b2c32fa84 .
