### ISSUE TITLE
only downloads to home folder?

### ISSUE THREAD

**Issue by simonm3** [floydwch/kaggle-cli#30]
I can "kg download" in my home folder. However if I am in a folder on a different drive it just hangs. And typically I want to put my data on a separate data volume.

**Comment by floydwch** [comment]
Please provide the config information in the folder you issue the download command.

i.e. issue following command in the folder.

```
kg config
```

**Comment by simonm3** [comment]
From the home folder:

Working config:
[('username', 'simonm3@gmail.com'), ('password', '********'),
('competition', 'dogs-vs-cats-redux-kernels-edition')]

from the folder on my volume:

Working config:

**Comment by floydwch** [comment]
OK, it seems that you issued the command from a folder with null config, and `kaggle-cli` didn't notify you.

I suggest you set the config in the volume folder again in the meantime.

```
kg config -u `username` -p `password` -c `dogs-vs-cats-redux-kernels-edition`
```

I'll add some detecting code against the null config.

**Comment by simonm3** [comment]
Ah I see. Makes sense to have a folder specific config as it holds the
project name but I agree an error message would help.

Also would be handy to have some sort of progress indicator for large files
but not sure how easy that is to include.

**Comment by priyankub** [comment]
I cannot kg download in another drive even if I put the whole command ie. kg download -u <username> -p <password> -c street-view-getting-started-with-julia

Also, in case I have a power cut and my network drops for a moment, will kg resume the download? I can see kg is still running in the background and though network connectivity resumed, I can say downloading did not resume because I do not see any of those processes in 'nethogs' which I used to see earlier. 
Would it be possible to add a resume functionality please on reconnection of network?

Thanks!

**Comment by simonm3** [comment]
This is not just about an error message. It is not possible to set a config in a folder outside the home folder. So i you want to download to a separate drive then it fails to find the config.

**Comment by floydwch** [comment]
@simonm3 now support resumable download in 0.9.0 .

**Comment by floydwch** [comment]
@simonm3 the latest version fixes the outside homedir config https://github.com/floydwch/kaggle-cli/commit/fe5db03891593025329a1ba40ba29ce29f6289c6 .

Could you help to test it?

**Comment by simonm3** [comment]
I tried kg config -u xxx -p xxx -c xxx
kg config does not show anything
kg download does not seem to do anything either tho did not wait long as I
understand there should be progress bar now.

**Comment by floydwch** [comment]
What's your OS, Python version?

BTW, the progress bar is not yet merged.

**Comment by simonm3** [comment]
Tried it on Windows py3.6

**Comment by floydwch** [comment]
And what's the working directory?

**Comment by floydwch** [comment]
What's the content in `/temp/.kaggle-cli/config`?

**Comment by simonm3** [comment]
just tried in a subsid of home folder. kg config shows nothing. config file
shows:

[user]
username = xxxx
password = xxxx

**Comment by simonm3** [comment]
This seems to work now.
