### ISSUE TITLE
Fix password not accepted / single quotes

### ISSUE THREAD

**Issue by swirlingsand** [floydwch/kaggle-cli#34]
It wasn't clear to me that we should be using single quotes for the password,
as formatting the string with double quotes is accepted (and works for username),
and a common sense check of running `kg config` returns 
the password as `'****'` with single quotes making it look like it was successful.

May I suggest this is added to documentation somewhere?

**Comment by floydwch** [comment]
Don't understand what you mean, but `kg config` just returns the current data in the config file, and the password is masked, so it displays `'********'` always if you set a password. Otherwise, it won't appear.

BTW, enrich the documentation is welcome.

**Comment by floydwch** [comment]
@swirlingsand did you mean that your password contains quote? if it's the case, you should quote the password by double quotes, it looks like `kg config -p "password with '"`.

I'm going to close the issue, if you still have problem, feel free to open issue.
