### ISSUE TITLE
submit => none type object has no attribute find

### ISSUE THREAD

**Issue by simonm3** [floydwch/kaggle-cli#35]
I get this error when I do "kg submit out.csv"
config is:

[('username', u's******@gmail.com'), ('password', '********'), ('competition', u'cats-vs-dogs-redux-kernels-edition')]

**Comment by stefat77** [comment]
same issue here:

kg submit submission.zip -c "Carvana Image Masking Challenge" -u USER -p PASS

**Comment by floydwch** [comment]
@stefat77 try `kg submit submission.zip -c carvana-image-masking-challenge -u USER -p PASS`.

**Comment by floydwch** [comment]
@simonm3 I can't find `cats-vs-dogs-redux-kernels-edition` but found `dogs-vs-cats-redux-kernels-edition`. I'm going to add warning tips for typo cases.

**Comment by floydwch** [comment]
fixed https://github.com/floydwch/kaggle-cli/commit/8f3d54dc1419e03cfcaf42bbfc0336de9200ce4f .
