### ISSUE TITLE
is it still working?

### ISSUE THREAD

**Issue by knguyen0105** [floydwch/kaggle-cli#4]
I just tried to submit to https://www.kaggle.com/c/facebook-v-predicting-check-ins/ and got an error

```
 kg config -c facebook-v-predicting-check-ins -u {USER} -p {PASS}
 kg submit data/Notebooks/submission2016.06.08.01.38.csv.zip -m '2nd submit'
no form matching nr 0
```

**Comment by floydwch** [comment]
@knguyen0105 hmm.. thanks for your report. Since I didn't participate in recent games, haven't noticed that.

I'll check it soon.

**Comment by knguyen0105** [comment]
Cool. Thank you. Hope it is an easy fix.

**Comment by matefh** [comment]
Thanks @floydwch for creating developing this. We do hope you continue to maintain it.

For now @knguyen0105 you can use this: https://github.com/matefh/kaggle-submit I wrote it over the weekend to help me with that same competition :)

**Comment by floydwch** [comment]
This issue has been fixed in the latest release, please `pip install -U kaggle-cli`.

BTW, the scoring response seems broken, in the meanwhile, there is no response of score after `kg submit`.

**Comment by matefh** [comment]
Thanks for fixing.

And yes scoring was acting weird with me too. It maybe related to the page being perceived as finished loading but not actually.

**Comment by floydwch** [comment]
@matefh Hmm.. nice insight.

**Comment by knguyen0105** [comment]
@floydwch @matefh Perfect. Just another 24 hours when my script finishes running. Thanks.
