### ISSUE TITLE
Feature request Proxy support via cli arg

### ISSUE THREAD

**Issue by mzavyalov** [floydwch/kaggle-cli#42]
Hi, 
is it possible to add a proxy support ?

I've added "export https_proxy=my_proxy", but it fails to download 

`HTTPSConnectionPool(host='www.kaggle.com', port=443): Max retries exceeded with url: /account/login (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f8e70ef6f50>: Failed to establish a new connection: [Errno 110] Connection timed out',))`

**Comment by mzavyalov** [comment]
[Just a finding](https://github.com/hickford/MechanicalSoup/issues/55). 
Might be able to pass 'proxies=' into browser.get() and browser.submit() [here](https://github.com/hickford/MechanicalSoup/issues/55)

**Comment by floydwch** [comment]
Env variables are case sensitive. Do you `export HTTPS_PROXY="proxy's url"` or `export https_proxy=my_proxy`? 

Since there is a way to set the proxy for the request, I'm thinking the design of this config. In the meanwhile, could you check your command?

**Comment by floydwch** [comment]
After my investigation, to add a proxy argument will affect all browser related operations, it involves changes at least 9 locations, and will increase when we add new features.

IMO, the best way to support proxy is following the [Requests' advice](http://docs.python-requests.org/en/master/user/advanced/#proxies).

I'll add it to README.
