### ISSUE TITLE
No such file, ".kaggle-cli/browser.pickle"

### ISSUE THREAD

**Issue by ankitdhall** [floydwch/kaggle-cli#44]
I tried to use the CLI to download a dataset,
`kg download -c ml-project-1 -u username -p password`
But received this error:
`[Errno 2] No such file or directory: '/home/user/.kaggle-cli/browser.pickle'`

This is in a miniconda environment. I have access to the competition online but am unable to download the data using the CLI.
It would be great help if this issue could be resolved.

Thanks,
Ankit

**Comment by floydwch** [comment]
Thanks for the report, it should be fixed via https://github.com/floydwch/kaggle-cli/commit/96684213600375ad9f57467f038e423d382bc7a1 . Please reinstall kaggle-cli.

**Comment by ankitdhall** [comment]
Thanks for the quick response. :+1:
