### ISSUE TITLE
No module named 'dummy_thread'

### ISSUE THREAD

**Issue by ankitdhall** [floydwch/kaggle-cli#46]
Hello,

I am trying to make a submission through `kg` however, whenever I run a command, I seem to get `No module named `dummy_thread'` error.  
However if I use `kg config` it displays config details.  

Thanks.

**Comment by floydwch** [comment]
What's your Python version?

**Comment by ankitdhall** [comment]
I am using Python 3.5.3.

**Comment by floydwch** [comment]
I guess it related with https://github.com/reclosedev/requests-cache/issues/83#issuecomment-310245006 .

**Comment by floydwch** [comment]
Fixed via https://github.com/floydwch/kaggle-cli/commit/b7456412ee7c1be6a2fb53a23969a093c279c079 .

And you have to remove the browser cache which is stored at `~/.kaggle-cli/browser.pickle` .

**Comment by floydwch** [comment]
Oops, it still exists.

**Comment by floydwch** [comment]
In the meanwhile, there is a workaround: `rm ~/kaggle-cli/browser.pickle` when you changed your Python from 2 to 3.

**Comment by floydwch** [comment]
Just use another approach to handle the pickle exception. Fixed via https://github.com/floydwch/kaggle-cli/commit/ddb82e52f61b704c7e318237dfd7bfbead83b180 .
