### ISSUE TITLE
Competition Not Found

### ISSUE THREAD

**Issue by jamesthompson275** [floydwch/kaggle-cli#49]
I am trying to submit to the `whats-cooking` competition as a late submission. I continually get a `competition not found` message, even though I do successfully retrieve my past submissions.  The same happens when I try a dummy submission to `carvana-image-masking-challenge` (though my submissions returns nothing). 
The `submit_url` in `submit.py` always 404's if I got to `[competition_url]/submissions/attach`, but if I go to `[competition_url]/submit` there is no longer a form with the id tags that `submit.py` looks for.

**Comment by jamesthompson275** [comment]
Here is the file I am trying to submit.  (Just change extension back to csv)
[test-submit.txt](https://github.com/floydwch/kaggle-cli/files/1358960/test-submit.txt)

**Comment by floydwch** [comment]
Kaggle seems to remove the old entry of submission.

I'll migrate kaggle-cli to the new entry of submission. Thanks for the report.

**Comment by floydwch** [comment]
fixed via https://github.com/floydwch/kaggle-cli/commit/f7d6dbdea9d64e09fa1e6efec2f95ff55adffad2 .
