### ISSUE TITLE
If user has run out of submissions no error is reported and the score for the last submission is displayed

### ISSUE THREAD

**Issue by queirozfcom** [floydwch/kaggle-cli#53]
This can cause confusion b/c users will just think their models are not changing the scores at all.

I think there should be some warning (maybe with the remaining time to wait) and no scores should be reported. 

(Maybe the response has some information we can use to detect whether there's been an error?)

**Comment by floydwch** [comment]
Yes, it can be detected. And it's fixed via https://github.com/floydwch/kaggle-cli/commit/d3c68a49fa65386a7c0c200dd4abb291f7ee57a3 .
