### ISSUE TITLE
Send submission and get score from python code directly

### ISSUE THREAD

**Issue by miguelgfierro** [floydwch/kaggle-cli#54]
Hi, 

The command line program works for me to do a submission to kaggle. However, I would like to get the result this submission made on the leaderboard. 

Is there an easy way to do this?

**Comment by floydwch** [comment]
Splitting the functionality to a core API is cool, but in the meanwhile you can use [subprocess](https://docs.python.org/3/library/subprocess.html) to execute Kaggle-cli from your Python code and get the result.

**Comment by miguelgfierro** [comment]
Thanks

**Comment by AwasthiMaddy** [comment]
An easy/naive way to do this - 
```
# Submit the submission on Kaggle
# subPath is submission file path
import os
cmd = 'kg submit '+subPath+' -u <your kaggle account username> -p <your kaggle passwd> -c <competition name>' #-m+msg
os.system(cmd)
```
