### ISSUE TITLE
password parsing broken

### ISSUE THREAD

**Issue by tcrensink** [floydwch/kaggle-cli#59]
data download and config break when passing `-p <password>` ; I suspect because it includes special characters such as : `!?*-[]`.  Error: `config: error: argument -p/--password: expected one argument`

**Comment by floydwch** [comment]
Try to use " to quote the password, e.g. "!@#$%$".

**Comment by vamsiuppala** [comment]
Has this been resolved? I am facing the same challenge

**Comment by floydwch** [comment]
@vamsiuppala did you quote your password with " " ?

**Comment by vamsiuppala** [comment]
I did. But changed the password and retried the same. It ran this time. Maybe it had something to do with the special characters in my password.
