### ISSUE TITLE
"kg download" isn't working

### ISSUE THREAD

**Issue by knguyen0105** [floydwch/kaggle-cli#6]
Hi, 

I run into an error when using 'kg download' to get data to my EC2.

```
$ kg download -u username -p passwprd -c grupo-bimbo-inventory-demand
no form matching nr 0
```

Thanks.

**Comment by floydwch** [comment]
Do you have accepted the competition rules on the Kaggle site?

**Comment by knguyen0105** [comment]
Yes, I did.

**Comment by knguyen0105** [comment]
My bad. My AMI on AWS was installed with the old kaggle-cli. Upgrade to new version fixes the problem. Sorry.
