### ISSUE TITLE
Bad request when submitting Kaggle entry

### ISSUE THREAD

**Issue by suzil** [floydwch/kaggle-cli#61]
On my GPU server, I've started getting 400 response when submitting Kaggle entries.
```
$ kg submit -v "sample_submission.csv" -u <my_username> -p <my_password> -c digit-recognizer -m "test submission"
Starting new HTTPS connection (1): www.kaggle.com
https://www.kaggle.com:443 "GET /c/digit-recognizer HTTP/1.1" 200 15896
https://www.kaggle.com:443 "POST /blobs/inbox/submissions HTTP/1.1" 200 303
https://www.kaggle.com:443 "POST /blobs/inbox/submissions/59d0cf127a134bc2a0c0a746aede19cf/240909/1512782907983 HTTP/1.1" 200 525
https://www.kaggle.com:443 "POST /c/digit-recognizer/submission.json HTTP/1.1" 400 235
list indices must be integers, not str
```
I wanted to make sure it wasn't my submission that was malformed, so I checked with the `sample_submission.csv` that came with the `digit-recognizer` competition. Same error. The sample submission file and my own submission file look fine. To be extra careful, I download one of my recently-successfully-submitted entries to Kaggle, and that submission CSV file gives me the exact same error message. 

I try with both Python 3 and Python 2.7. I am using `kaggle-cli 0.12.13`. I'm SSH'd into a remote machine and I am using a VPN.

**Comment by suzil** [comment]
Found out that I reached the team limit of submissions. Maybe a better error message could be added here?

**Comment by floydwch** [comment]
Thanks for the report. The error message should be handed. I'll check it.
