### ISSUE TITLE
encryption 

### ISSUE THREAD

**Issue by yitang** [floydwch/kaggle-cli#7]
Hi, thanks for writing this package. I start to use it and it works brilliantly. I wonder difficult it is to enable this package read an encrypted configuration file, like config.gpg?

**Comment by floydwch** [comment]
Interesting. However, the key is still stored on the local. If the local is compromised, the encryption would be also broke.

The config used currently is a plaintext. If you just need it obscure, we can xor it(the password only?) or use symmetric-key encryption.

**Comment by yitang** [comment]
I personally run kaggle competition locally, but it would be good for other users who run competition on a shared serves. There's a top player got banned because his colleague submitted his work stored in a shared server. 

I've only used gpg with symmetric encryption before and it works for me. not sure about xor though.

**Comment by floydwch** [comment]
@yitang Well, it seems you lose control of file access in the case you mentioned. Since the kaggle-cli config is stored at `~/.kaggle-cli/config`, it won't be accessed by others if the access mode set correctly, i.e., `chmod 600 ~/.kaggle-cli/config`.

**Comment by yitang** [comment]
brilliant. This would solve my problem. thanks.

**Comment by floydwch** [comment]
I'll directly close this issue, and feel free to ask if you still have problem.

**Comment by floydwch** [comment]
Oh, I think it should chmod the config automatically, therefore reopen it.

**Comment by yitang** [comment]
that would really good. thanks.

**Comment by floydwch** [comment]
fixed via https://github.com/floydwch/kaggle-cli/commit/70f6ebc516dbc023f28c1f459d440df6b784a437.
