### ISSUE TITLE
one configure file per competition/folder

### ISSUE THREAD

**Issue by yitang** [floydwch/kaggle-cli#8]
Hello again, I guess there must be other users like me who participate at least one competition at a time, which makes me think of having one configure file per competition, and the easy way to implement it is to set the default configuration to ./.kaggle_cli.

**Comment by floydwch** [comment]
We can implement a hierarchical config to support it, i.e., store user config at `~/.kaggle-cli`, and store competition config at `./.kaggle-cli`.

**Comment by yitang** [comment]
this sounds good!

**Comment by floydwch** [comment]
@yitang 

I've implemented such function in the latest version on PyPI. See the usage https://github.com/floydwch/kaggle-cli#config .

There is two versions of config: local and global.

The global config is stored at `~/.kaggle-cli/config` and the local one is stored at `./.kaggle-cli/config` or the current directory's ancestor which contains a `.kaggle-cli` directory. I.e. like `.git`'s design. The local config overrides the global one.

However, I don't participate in recent kaggle competitions, could you have the chance to help testing it?

**Comment by yitang** [comment]
@floydwch 

Of course. But I have a problem in upgrading kaggle-cli. It requires an upgrade in lxml package which I am unable to install on my current debian machine. I messed up the APT and it can't solve the package dependencies. 

I will try on my Mac later.

**Comment by yitang** [comment]
relates to #10

**Comment by floydwch** [comment]
I rewrote the problematic config, see https://github.com/floydwch/kaggle-cli/commit/ddc71bb7e28811a305758fe983a721341f29a4e0 .

And cleaning the issue list, if you still have the problem, please open a new issue.
