### ISSUE TITLE
zip files download as html

### ISSUE THREAD

**Issue by baogorek** [floydwch/kaggle-cli#9]
I just ran a kg download with flag "-c ultrasound-nerve-segmentation", and the .zip files that downloaded were just html files rather than actually zip files. It looks like Kaggle might be doing some javascript magic to prevent your cli tool from working.

[ec2-user@ip-10-236-17-221 test]$ ls -l
total 64
-rw-rw-r-- 1 ec2-user ec2-user 15424 Jul 31 22:14 sample_submission.csv.zip
-rw-rw-r-- 1 ec2-user ec2-user 15390 Jul 31 22:14 test.zip
-rw-rw-r-- 1 ec2-user ec2-user 15412 Jul 31 22:14 train_masks.csv.zip
-rw-rw-r-- 1 ec2-user ec2-user 15392 Jul 31 22:14 train.zip

**Comment by floydwch** [comment]
Do you have accepted the agreement of the competition on Kaggle's site before this operation? Or checking your username and password.

I can download these files from cli.

**Comment by yitang** [comment]
I had same problems.

**Comment by floydwch** [comment]
Please provide the content in the file.

**Comment by nateGeorge** [comment]
You most likely have your password and/or username wrong.  If you only have a login through a linked account (e.g. Google), you will have to [reset your password here](https://www.kaggle.com/forgot/password), and make sure to use your Kaggle username listed on your profile page.
